name: ui-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-ui-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Create .env from secrets
        run: |
          {
            echo "BASE_URL=${{ secrets.BASE_URL }}"
            echo "USER_EMAIL=${{ secrets.USER_EMAIL }}"
            echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}"
            echo "PW_BROWSER=chromium"
            echo "PW_HEADLESS=true"
            echo "PW_TIMEOUT=10000"
            echo "RECORD_VIDEO=false"
          } >> .env

      # (khuyến nghị) Bật trace/video/screenshot khi fail
      - name: Prepare Playwright artifacts folder
        run: mkdir -p artifacts

      - name: Run tests (pytest + Allure results)
        env:
          # bạn có thể đọc các biến này trong code nếu cần
          PYTEST_ADDOPTS: "-q -m ui --alluredir=allure-results --maxfail=1"
        run: |
          pytest

      # Build HTML Allure
      - name: Install Allure CLI
        run: |
          npm i -g allure-commandline --no-audit --no-fund

      - name: Generate Allure HTML report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean

      # Upload raw results + HTML để tải về xem
      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 7

      - name: Upload Allure HTML (downloadable)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 7

      # (tuỳ chọn) Upload video/trace/screenshot nếu bạn lưu ra ./artifacts
      - name: Upload Playwright artifacts
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: pw-artifacts
          path: artifacts
          retention-days: 7
