name: ui-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 5"   # 9h sáng thứ 6 (giờ VN)

permissions:
  contents: read

concurrency:
  group: ci-web-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright browsers (Python)
        run: python -m playwright install --with-deps chromium
      - name: Run tests (pytest + Allure results)
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          HEADLESS: 'true'
          BROWSER: 'chromium'
        run: pytest -m smoke --alluredir=allure-results --tb=short -v
      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-failure-artifacts
          path: |
            test-results/
            screenshots/
            videos/
          if-no-files-found: ignore
          retention-days: 14
      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: error
          retention-days: 30

  report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download allure-results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      - name: Setup Java (Allure CLI)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Allure CLI
        run: npm i -g allure-commandline@2.24.1
      - name: Generate Allure HTML report
        run: |
          allure generate allure-results -o allure-report --clean
          echo "# Test Report" > allure-report/README.md
          echo "Generated: $(date)" >> allure-report/README.md
          echo "Workflow: ${{ github.workflow }}" >> allure-report/README.md
          echo "Run ID: ${{ github.run_id }}" >> allure-report/README.md
      - name: Upload Allure HTML (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-html
          path: allure-report
          if-no-files-found: error
          retention-days: 30

  notify:
    needs: [test, report]
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
    steps:
      - name: Summary (tests failed)
        if: needs.test.result == 'failure'
        run: |
          echo "::error title=E2E Tests Failed::Tests failed on main. Download 'allure-report-html' artifact in this run to view the report."
      - name: Summary (tests passed)
        if: needs.test.result == 'success'
        run: |
          echo "::notice title=E2E Tests Passed::All tests passed. Download 'allure-report-html' artifact in this run to view the report."
